name: "Action yml"
author: "codermak"
description: "action.yml test"
inputs:
  token:
    description: "The authentication value used with the Slack API."
    required: false
outputs:
  ok:
    description: "If the request completed without returning errors."
  response:
    description: "A JSON stringified version of the Slack API response."
  time:
    description: "The Unix epoch time that the step completed."
  channel_id:
    description: "The channel ID returned with some of the Slack API methods."
  thread_ts:
    description: "The timestamp of a parent Slack message with threaded replies."
  ts:
    description: "The timestamp of a Slack message or event in the response."
runs:
  using: "node20"
  main: "dist/poc.js"
